# Dependabot Configuration <https://dependabot.com/docs/config-file/>
version: 1
update_configs:
- package_manager: "javascript"
  directory: "/"
  update_schedule: "live"
  ignored_updates:
  # eslint packages must be updated together due to peerDependencies.
  # Ignore all but @kevinoid/eslint-config, which declares peerDependencies.
  #
  # FIXME: Want to ignore updates outside of peerDependencies (usually major).
  # If using package-lock.json, want minor/patch.
  # Can't currently configure update_type for ignored_updates.
  # https://github.com/dependabot/feedback/issues/340#issuecomment-586450312
  - match:
      dependency_name: "eslint*"
