# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: Node.js CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
  push:
    branches-ignore:
    - template
  schedule:
  # Run once a day (at 8:40 AM UTC) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '40 8 * * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  test-primary:
    name: Lint and Test on Node.js * x64 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        # Note: '*' is "latest LTS version" (without check-latest, it would be
        # "latest LTS version in local cache") because it first checks
        # https://github.com/actions/node-versions/releases then falls back to
        # https://nodejs.org/dist/index.json
        # For explanation and discussion, see:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version=
        # https://github.com/actions/setup-node/issues/61#issuecomment-577548687
        # https://github.com/actions/setup-node/issues/164#issuecomment-648999618
        # https://github.com/actions/setup-node/pull/104
        #
        # Support for "current"/"latest"/"node" was added in v3.2.0
        # https://github.com/actions/setup-node/pull/483
        node-version: latest
        architecture: x64
        check-latest: true
    - name: Display Node.js version
      run: node --version
    - name: Harden npm
      run: >-
        npm config set allow-git=none &&
        npm config set ignore-scripts=true
    # Workaround for https://github.com/bcoe/c8/issues/582
    # Only apply to Node 26, since require() of ESM not supported on Node <20.19
    # TODO [c8@>=12]: Remove this workaround.
    - name: Override yargs for c8 on Node 26
      shell: bash
      run: >-
        jq '.overrides.c8.yargs |= "^18.0.0"' package.json >package.json.new &&
        mv -f package.json.new package.json
    - name: Install dependencies
      run: npm install --strict-peer-deps
    - name: Lint
      run: npm run lint
    - name: Run tests
      run: npm run test-unit-cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354  # v6.0.1
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e  # v2.3.7
      with:
        # Ignore intermittent server errors which are out of our control.
        # FIXME: Would like to ignore intermittent server errors only.  See:
        # https://github.com/coverallsapp/github-action/issues/261
        fail-on-error: false
        flag-name: 'ubuntu-latest_x64_*'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  test-secondary:
    # Only test secondary platforms if primary test platform passed
    needs:
    - test-primary
    name: >-
      Test on Node.js ${{ matrix.node }} ${{ matrix.arch }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
        # Uncomment if package needs testing on different architectures
        # - x86
        - x64
        os:
        # Uncomment if package needs testing on macOS:
        # - macos-latest
        - ubuntu-latest
        - windows-latest
        node:
        - '20.0'
        - latest
        exclude:
        # Exclude os/version already run in test-primary
        - arch: x64
          os: ubuntu-latest
          node: latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        node-version: ${{ matrix.node }}
        architecture: ${{ matrix.arch }}
        check-latest: ${{ matrix.node == '*' }}
    - name: Display Node.js version
      run: node --version
    - name: Harden npm
      run: >-
        npm config set allow-git=none &&
        npm config set ignore-scripts=true
    # Workaround for https://github.com/bcoe/c8/issues/582
    # Only apply to Node 26, since require() of ESM not supported on Node <20.19
    # TODO [c8@>=12]: Remove this workaround.
    - name: Override yargs for c8 on Node 26
      if: matrix.node == 'latest'
      shell: bash
      run: >-
        jq '.overrides.c8.yargs |= "^18.0.0"' package.json >package.json.new &&
        mv -f package.json.new package.json
    - name: Install dependencies
      run: npm install --strict-peer-deps
    - name: Run tests
      run: npm run test-unit-cov
    # Note: Not uploading to Codecov, due to poor support for matrix builds
    # https://github.com/codecov/codecov-action/issues/40
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e  # v2.3.7
      with:
        # Ignore intermittent server errors which are out of our control.
        # FIXME: Would like to ignore intermittent server errors only.  See:
        # https://github.com/coverallsapp/github-action/issues/261
        fail-on-error: false
        flag-name: ${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.node }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  finish:
    needs: test-secondary
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e  # v2.3.7
      with:
        # Ignore intermittent server errors which are out of our control.
        # FIXME: Would like to ignore intermittent server errors only.  See:
        # https://github.com/coverallsapp/github-action/issues/261
        fail-on-error: false
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
