# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: Node.js CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
  push:
    branches-ignore:
    - template
  schedule:
  # Run once a day (at 8:40 AM UTC) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '40 8 * * *'

jobs:
  test-primary:
    name: Lint and Test on Node.js * x64 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        # '*' is "latest" (without check-latest, it is "latest in local cache")
        # https://github.com/actions/setup-node/issues/61#issuecomment-577548687
        # https://github.com/actions/setup-node/issues/164#issuecomment-648999618
        # https://github.com/actions/setup-node/pull/104
        node-version: '*'
        architecture: x64
        check-latest: true
    - name: Display Node.js version
      run: node --version
    - name: Install dependencies
      # Note: Not using --strict-peer-deps until npm@8.1.1 ships with Node.js
      # due to https://github.com/npm/cli/issues/3868
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Run tests
      run: npm run test-unit-cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Upload coverage to Coveralls
      # Note: @master is currently the only version
      # https://github.com/coverallsapp/github-action/issues/11
      uses: coverallsapp/github-action@master
      # Ignore intermittent server errors (which are out of our control).
      # https://github.com/coverallsapp/github-action/issues/9
      # https://github.com/coverallsapp/github-action/issues/79
      # https://github.com/coverallsapp/github-action/issues/93
      continue-on-error: true
      with:
        flag-name: 'ubuntu-latest_x64_*'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  test-secondary:
    # Only test secondary platforms if primary test platform passed
    needs:
    - test-primary
    name: >-
      Test on Node.js ${{ matrix.node }} ${{ matrix.arch }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
        # Uncomment if package needs testing on different architectures
        # - x86
        - x64
        os:
        # Uncomment if package needs testing on macOS:
        # - macos-latest
        - ubuntu-latest
        - windows-latest
        node:
        - '12.0'
        - '*'
        exclude:
        # Exclude os/version already run in test-primary
        - arch: x64
          os: ubuntu-latest
          node: '*'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        architecture: ${{ matrix.arch }}
        check-latest: ${{ matrix.node == '*' }}
    - name: Display Node.js version
      run: node --version
    - name: Install dependencies
      # Note: Not using --strict-peer-deps until npm@8.1.1 ships with Node.js
      # due to https://github.com/npm/cli/issues/3868
      run: npm install
    - name: Run tests
      run: npm run test-unit-cov
    # Note: Not uploading to Codecov, due to poor support for matrix builds
    # https://github.com/codecov/codecov-action/issues/40
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        flag-name: ${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.node }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  finish:
    needs: test-secondary
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
